pipeline {

    agent any

    environment {
        FRONTEND_IMAGE = "drishh/myapp-frontend"
        BACKEND_IMAGE = "drishh/myapp-backend"
    }

    stages {

        stage('Build Docker Images') {
            steps {
                dir('my-app') {
                    bat 'docker build -t %FRONTEND_IMAGE% ./frontend'
                    bat 'docker build -t %BACKEND_IMAGE% ./backend'
                }
            }
        }

        stage('Push Images') {
            steps {
                dir('my-app') {
                    bat 'docker push %FRONTEND_IMAGE%'
                    bat 'docker push %BACKEND_IMAGE%'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('my-app') {
                    bat 'docker compose up -d'
                }
            }
        }
    }
}